import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Providers } from "./providers";
import { ModelProvider } from "@/lib/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "LLM Net",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} bg-neutral-100 dark:bg-neutral-900`}>
        <Providers>
          <ModelProvider>
            <div>
              <Navbar />
              {children}
            </div>
          </ModelProvider>
        </Providers>
      </body>
    </html>
  );
}
