import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Providers } from "./providers";
import { ModelProvider } from "@/lib/context";
import { SpeedInsights } from "@vercel/speed-insights/next";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "LLM Net",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} bg-[#fafafa] dark:bg-neutral-900`}>
        <Providers>
          <ModelProvider>
            <div className="flex flex-col min-h-screen justify-between">
              <SpeedInsights />
              <Navbar />
              {children}
              <Footer />
            </div>
          </ModelProvider>
        </Providers>
      </body>
    </html>
  );
}
